name: Java CI 

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up JDK 16
      uses: actions/setup-java@v1
      with:
        java-version: 16

    - name: Build with Gradle
      uses: GabrielBB/xvfb-action@v1
      with:
          run: ./gradlew clean build

    - name: Install zip
      uses: montudor/action-zip@v1
